_target_: pytorch_lightning.callbacks.ModelCheckpoint

monitor: 
mode: 
filename: best-${.monitor}-{${.monitor}}-epoch-{epoch}
auto_insert_metric_name: false
dirpath: ${callback.dirpath}/checkpoints
every_n_epochs: 1
save_top_k: 1
save_last: false
save_on_train_epoch_end: false
