_target_: pytorch_lightning.callbacks.ModelCheckpoint

filename: last-epoch-{epoch}
auto_insert_metric_name: false
# dirpath: /work/achandrasekaran/asymov  # /ps/scratch/achandrasekaran/asymov/checkpoints  # ${path.working_dir}/checkpoints
dirpath: ${callback.dirpath}/checkpoints
every_n_epochs: 1
save_top_k: 1
save_last: false #to optimize
