hydra:
  run:
    dir: .
  output_subdir: null

seed: 1234

logger_level: INFO
folder: ???

split: ???

ckpt_name: last.ckpt
ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}

# if jointstype == vertices
# can specify the gender
# neutral / male / female
gender: neutral

# Composing nested config with default
defaults:
  - data: null
  - machine: null
  - trainer: null
  - sampler: variable_conseq
  - /path@path
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_
