hydra:
  run:
    dir: outputs/${data.name}/${experiment}/${run_id}

# Global configurations shared between different modules
experiment: ???

seed: 1234

logger_level: INFO
run_id: ${generate_id:}
resume_ckpt_path:
wandb_api_keys:
  darsh: 57f6d5aab6f1a78b78fb181dcf32dfeca0e65f79
  arjun: bac3a003428df951a8e0b9e3878002a3227bbf0c
  shared: 2ec984489f9445078fa14448bc7da1f0c3604db6
user: 

num_mw_clusters: ???
# Composing nested config with default
defaults:
  - data: kit-xyz-motion-word
  - model: asymov
  - machine: server
  - trainer: gpu
  - sampler: variable_conseq
  - logger: wandb
  - callback: base
  - /path@path
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: custom
  - _self_

data:
  transforms:
    normalization: true

callback:
  best_ckpt_monitors: [['total/val', 'min'], ['Metrics/bleu_text2mw/val', 'max'], ['Metrics/acc_text2mw/val', 'max'], ['Metrics/MPJPE_naive_none_text2mw/val', 'min']]

  viz_ckpts: false
  viz_ckpt:
    start_epoch: 100
    every_n_epochs: 5

  last_ckpt:
    every_n_epochs: 10

transforms: ${data.transforms}
