_target_: temos.model.losses.TemosComputeLosses

mode: motion_word

# Loss terms
## Reconstruction losses
lmd_mw_recons_text2mw: 1.0
lmd_mw_recons_mw2mw: ${.lmd_mw_recons_text2mw}

## Latent spaces losses
lmd_latent: 1.0e-5 #used for either L1 or Cosine
lmd_kl: 1.0e-05
# lmd_cos: 1.0e-05

# Ablations
loss_on_both: true

force_loss_on_jfeats: false
ablation_no_kl_combine: false
ablation_no_kl_gaussian: false
ablation_no_motionencoder: false

# Text => motion_words
recons_text2mw: ${.lmd_mw_recons_text2mw}
recons_text2mw_func: ${model.func_recons}

# motion_words => motion_words
recons_mw2mw: ${.lmd_mw_recons_mw2mw}
recons_mw2mw_func: ${model.func_recons}

# Latent space losses
latent_manifold: ${.lmd_latent}
latent_manifold_func: ${model.func_latent}

#Cosine similarity loss
cosine_similarity: ${.lmd_latent}
cosine_similarity_func: ${model.func_cos}

# VAE losses
kl_text: ${.lmd_kl}
kl_text_func: ${model.func_kl}

kl_motion: ${.lmd_kl}
kl_motion_func: ${model.func_kl}

kl_text2motion: ${.lmd_kl}
kl_text2motion_func: ${model.func_kl}

kl_motion2text: ${.lmd_kl}
kl_motion2text_func: ${model.func_kl}
