name: bert_actor
_target_: temos.model.textencoder.distilbert_actor.DistilbertActorAgnosticEncoder

latent_dim: ${model.latent_dim}
vae: ${model.vae}

ff_size: ${model.ff_size}
num_layers: ${model.num_layers}
num_head: ${model.num_head}
dropout: ${model.dropout}
activation: ${model.activation}

finetune: false
modelpath: ${path.deps}/bert-base-uncased
